### ISSUE TITLE
Getting build error with RN version 0.27

### ISSUE THREAD

**Issue by vidyuthd** [aakashns/react-native-dialogs#32] opened 2016-07-10 19:46 UTC
Hi, I m getting the following build error in a project having multiple dependencies, 
`MainActivity.java:42: error: method does not override or implement a method from a supertype @Override  ^1 error :app:compileDebugJavaWithJavac FAILED`

I suspect this is due to - [this](https://github.com/aakashns/react-native-dialogs/blob/master/android/build.gradle#L31). This should be related to RN 0.29 breaking changes regarding android template - [here](https://github.com/facebook/react-native/releases/tag/v0.29.0). Since the plugin downloads latest version of RN jar to compile against, it forces the app to compile with it, which breaks due to changes (third party plugins now no longer added in Activity, but new App file which extend android.app.Application and implement ReactApplication)

Going on, if any user decides to use RN 0.29 , I don't see any problem in using this, but in case he decides to use lesser version, the build would fail. Can you check please ? Thanks.

**Comment by vonovak** [comment] 2017-11-30 23:31
I'm closing this since the issue is outdated.

**Closed by vonovak** 2017-11-30 23:31 UTC
