### ISSUE TITLE
Configure so that rnpm link works

### ISSUE THREAD

**Issue by cancan101** [aakashns/react-native-dialogs#21] opened 2016-05-07 18:20 UTC
Right now `maven { url "https://jitpack.io" }` is not added by `rnpm link`

**Comment by VinceBT** [comment] 2016-06-03 11:30
+1

**Comment by meiraleal** [comment] 2016-06-24 14:07
Good move to include a rnpm automatic installation.

**Comment by vonovak** [comment] 2017-09-17 17:49
closing since there is very little information provided and the issue is old. feel free to reopen.

**Closed by vonovak** 2017-09-17 17:49 UTC
