### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by linonetwo** [aakashns/react-native-dialogs#23] opened 2016-05-29 11:06 UTC
By calling 
dialog.show({});

In DialogAndroid.js line 67
NativeModules.DialogAndroid.show(finalOptions, callbackFunc);

says undefined is not an object.

seems NativeModules.DialogAndroid is deprecated?

**Comment by saemie** [comment] 2016-07-01 16:06
I'm having the same issue, did you find a solution?

**Comment by linonetwo** [comment] 2016-07-01 16:09
@saemie No, I switch to react-native-model .....

**Comment by vonovak** [comment] 2017-09-17 17:50
closing since there is very little information provided and the issue is old. feel free to reopen.

**Closed by vonovak** 2017-09-17 17:50 UTC
